### ISSUE TITLE
Playground example does not work

### ISSUE THREAD

**Issue by chipironcin** [cemheren/konvoy.io#1]
The example code at https://konvoy.io/playground/ doesnt work out of the box.
Editing it produces the same output.

```
Error running your code. Error: Timed out after 30000 ms while trying to connect to Chrome! The only Chrome revision guaranteed to work is r526987
```

**Comment by cemheren** [comment]
Hi, which example did you try? Are you getting this with the default code? 

const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.goto('https://example.com');
console.log(await page.content());
await page.screenshot({path: 'screenshot.png'});
await browser.close();

?

**Comment by chipironcin** [comment]
Weird, now it works.
Great tool BTW!
Very useful and does the work for you (L)

**Comment by cemheren** [comment]
Thanks! Any suggestions to make it better are always welcome :)
